---
- name: Export Cilium images on CP-1
  hosts: cp-1
  become: true

  vars:
    image_bundle: "/tmp/cilium-images.tar"

    cilium_images:
      - "quay.io/cilium/cilium-envoy:v1.37.5-1786810558-766ccfb37260a43e9d228837aa84ce3faf9f64e7"
      - "quay.io/cilium/cilium:v1.20.1"
      - "quay.io/cilium/operator-generic:v1.20.1"

  tasks:
    - name: Export Cilium images into a single tar
      ansible.builtin.command:
        cmd: >-
          /usr/local/bin/ctr -n k8s.io images export
          {{ image_bundle }}
          {{ cilium_images | join(' ') }}
      args:
        creates: "{{ image_bundle }}"


- name: Copy and import Cilium images on k8s nodes
  hosts: k8s_nodes
  become: true

  vars:
    image_bundle: "/tmp/cilium-images.tar"

  tasks:
    - name: Copy image bundle from CP-1 to this node
      ansible.builtin.command:
        cmd: >-
          scp
          /tmp/cilium-images.tar
          {{ ansible_user | default('root') }}@{{ ansible_host | default(inventory_hostname) }}:/tmp/cilium-images.tar
      delegate_to: cp-1

    - name: Import Cilium images into k8s.io namespace
      ansible.builtin.command:
        cmd: /usr/local/bin/ctr -n k8s.io images import /tmp/cilium-images.tar

    - name: Verify Cilium images
      ansible.builtin.command:
        cmd: /usr/local/bin/ctr -n k8s.io images ls
      register: cilium_images_check
      changed_when: false

    - name: Show imported Cilium images
      ansible.builtin.debug:
        msg: "{{ cilium_images_check.stdout_lines | select('search', 'cilium') | list }}"