[control-planes]
cp-1              ansible_host=192.168.55.118     ansible_connection=ssh      ansible_user=parsa
cp-2              ansible_host=192.168.55.119     ansible_connection=ssh      ansible_user=parsa
cp-3              ansible_host=192.168.55.120     ansible_connection=ssh      ansible_user=parsa


[workers]
node-1            ansible_host=192.168.55.121     ansible_connection=ssh      ansible_user=parsa
node-2            ansible_host=192.168.55.122     ansible_connection=ssh      ansible_user=parsa

[lb]
app-lb            ansible_host=192.168.55.123     ansible_connection=ssh      ansible_user=parsa

[k8s_nodes:children]
control-planes
workers
